version: "3.8"

services:
  p-postgres:
    image: postgres:latest
    container_name: p-postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5430:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  tp-postgres:
    image: postgres:latest
    container_name: tp-postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tpdb
    ports:
      - "5431:5432"
    volumes:
      - ./third-party/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  tp-api:
    build: ./third-party
    container_name: tp-api
    restart: always
    environment:
      POSTGRES_HOST: tp-postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: tpdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    depends_on:
      - tp-postgres
    ports:
      - "3007:3007"

  gql-api:
    build: ./graphql-api
    container_name: gql-api
    restart: always
    environment:
      POSTGRES_HOST: p-postgres
      TP_API_HOST: tp-api
      POSTGRES_PORT: 5432
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    depends_on:
      - p-postgres
      - tp-api
    ports:
      - "4000:4000"

# TODO: add health checks