version: "3.8"

services:
  postgres-p:
    image: postgres:latest
    container_name: postgres-p
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5430:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  postgres-tp:
    image: postgres:latest
    container_name: postgres-tp
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tpdb
    ports:
      - "5431:5432"
    volumes:
      - ./third-party/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: ./third-party  # Path to your API's Dockerfile
    container_name: tp-api
    restart: always
    environment:
      POSTGRES_HOST: postgres-tp  # Connects to postgres-tp
      POSTGRES_PORT: 5432
      POSTGRES_DB: tpdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    depends_on:
      - postgres-tp
    ports:
      - "3007:3007"  # Maps container port to host
